package com.example.sellapy.navigation

const val ROUT_HOME="home"
const val ROUT_ABOUT="about"
const val ROUT_DETAIL="details"
const val ROUT_CONTACT="contact"
const val ROUT_DASHBOARD="dashboard"
const val ROUT_SPLASH="splash"
const val ROUT_INTENT="intent"
const val ROUT_SIGNUP="signup"
const val ROUT_LOGIN="login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val ADD_STUDENT_URL = "add_student"
const val VIEW_STUDENT_URL = "view_student"
